#**INTELLIGENZA ARTIFICIALE: TECNOLOGIE, MODELLI E APPLICAZIONI**

---

**Teaching Assistants:** Lorenzo Vaiani

**Practice:** Topic Modeling

Occurrence-based representations are high-dimensional, what is the dimension of the generated TF-IDF vector representation?
Topic modeling focuses on capturing latent topics in large document corpora.

The data collection used in this second part of the practice is provided [here](https://raw.githubusercontent.com/MorenoLaQuatra/DeepNLP/main/practices/P1/CovidFake_filtered.csv) - [source: Zenodo](https://zenodo.org/record/4282522#.YVdCXcbOOpd)

# Exercise 1

Latent Semantic Indexing (LSI) models underlying concepts by using SVD (Singular Value Decomposition).

Use [gensim](https://radimrehurek.com/gensim/) library to:
1. Create a corpus composed of the headlines contained in the data collection.
2. Generate a [dictionary](https://radimrehurek.com/gensim/corpora/dictionary.html) to create a word -> id mapping (required by LSI module).
3. Using the dictionary, preprocess the corpus to obtain the representation required for LSI model training ([documentation here](https://radimrehurek.com/gensim/models/lsimodel.html)).
4. Inspect the top-5 topics generated by the LSI model for the analysed corpus.

In [1]:
#! pip uninstall numpy
#! pip install numpy==1.26.4
#! pip install --upgrade scipy gensim

In [2]:
import pandas as pd
df_tmodeling = pd.read_csv('CovidFake_filtered.csv')

In [3]:
# generating the corpus
corpus = df_tmodeling["headlines"].tolist()
corpus = [s.split() for s in corpus]
print (corpus[:10])

[['A', 'post', 'claims', 'compulsory', 'vacination', 'violates', 'the', 'principles', 'of', 'bioethics,', 'that', 'coronavirus', "doesn't", 'exist,', 'that', 'the', 'PCR', 'test', 'returns', 'many', 'false', 'positives,', 'and', 'that', 'influenza', 'vaccine', 'is', 'related', 'to', 'COVID-19.'], ['A', 'photo', 'claims', 'that', 'this', 'person', 'is', 'a', 'doctor', 'who', 'died', 'after', 'attending', 'to', 'too', 'many', 'COVID-19', 'patinents', 'in', 'Hospital', 'Muñiz', 'in', 'Buenos', 'Aires.'], ['Post', 'about', 'a', 'video', 'claims', 'that', 'it', 'is', 'a', 'protest', 'against', 'confination', 'in', 'the', 'town', 'of', 'Aranda', 'de', 'Duero', '(Burgos)'], ['All', 'deaths', 'by', 'respiratory', 'failure', 'and', 'pneumonia', 'are', 'being', 'registered', 'as', 'COVID-19,', 'according', 'to', 'the', 'Civil', 'Registry', 'website.'], ['The', 'dean', 'of', 'the', 'College', 'of', 'Biologists', 'of', 'Euskadi', 'states', 'that', 'there', 'are', 'a', 'lot', 'of', 'PCR', 'false', 'positives', 'and', 'asymptomatic', "don't", 'spread', 'coronavirus.'], ['Households', 'with', 'COVID-19', 'patients', 'in', 'Porto', 'Alegre,', 'Campo', 'Grande', 'and', 'Santo', 'Antônio', 'da', 'Platina', 'must', 'put', 'a', 'red', 'ribbon', 'on', 'their', 'garbage', 'bags.', 'Garbagemen', 'are', 'instructed', 'to', 'handle', 'them', 'in', 'a', 'safer', 'way'], ['A', 'chain', 'lists', 'recommendations', 'to', 'prevent', 'and', 'treat', 'coronavirus.'], ['60,000', 'Argentinian', 'companies', 'have', 'closed', 'due', 'to', 'COVID-19;', 'also,', 'all', 'companies', 'receiving', 'government', 'aid', 'during', 'the', 'pandemic', 'will', 'be', 'expropriated', 'by', 'the', 'government'], ['Social', 'media', 'posts', 'criticize', 'a', 'photo', 'from', 'smiling', 'president', 'of', 'the', 'Goverment', 'Pedro', 'Sánchez', 'during', 'his', 'holidays', 'after', 'thousands', 'died', 'from', 'COVID-19'], ['CDC', 'has', 'released', 'an', 'update', 'on', 'how', 'the', 'novel', 'coronavirus', 'can', 'be', 'transmitted']]

In [4]:
# constructing dictionary and processing the corpus
from gensim.corpora.dictionary import Dictionary
tm_dict = Dictionary(corpus)
processed_corpus = [tm_dict.doc2bow(text) for text in corpus]

In [5]:
# training LSI model
from gensim.models import LsiModel
model = LsiModel(processed_corpus, id2word=tm_dict)
model.print_topics(5)

[(0,
  '0.636*"the" + 0.389*"of" + 0.314*"in" + 0.280*"a" + 0.254*"to" + 0.179*"and" + 0.155*"that" + 0.121*"is" + 0.107*"coronavirus" + 0.106*"A"'),
 (1,
  '-0.629*"the" + 0.598*"a" + 0.386*"in" + 0.105*"A" + 0.097*"and" + 0.078*"has" + 0.077*"COVID-19" + 0.071*"video" + 0.070*"on" + 0.064*"been"'),
 (2,
  '0.709*"to" + -0.633*"of" + 0.137*"and" + 0.123*"is" + 0.071*"for" + 0.069*"be" + 0.054*"that" + 0.051*"are" + 0.049*"from" + 0.048*"due"'),
 (3,
  '0.734*"in" + -0.428*"of" + -0.363*"to" + -0.283*"a" + 0.172*"the" + 0.097*"coronavirus" + -0.046*"from" + 0.040*"was" + -0.037*"COVID-19." + -0.034*"on"'),
 (4,
  '0.479*"to" + 0.425*"of" + -0.407*"a" + 0.391*"in" + -0.259*"that" + -0.240*"the" + -0.213*"is" + -0.187*"and" + -0.115*"for" + -0.075*"coronavirus"')]

# Exercise 2

Leveraging the same corpus used for LSI model generation, apply LDA modeling setting the number of topics to 5. Display the words most contributing to the those topics according to the LDA model.

In [6]:
from gensim.models.ldamodel import LdaModel
lda = LdaModel(processed_corpus, id2word=tm_dict, num_topics=5)
lda.print_topics(5)

[(0,
  '0.048*"in" + 0.047*"the" + 0.039*"a" + 0.035*"of" + 0.017*"to" + 0.016*"A" + 0.014*"coronavirus" + 0.013*"on" + 0.012*"and" + 0.011*"has"'),
 (1,
  '0.038*"the" + 0.031*"of" + 0.030*"is" + 0.025*"coronavirus" + 0.022*"a" + 0.019*"in" + 0.016*"that" + 0.014*"and" + 0.014*"COVID-19" + 0.013*"to"'),
 (2,
  '0.018*"coronavirus" + 0.017*"in" + 0.015*"the" + 0.014*"to" + 0.013*"with" + 0.013*"a" + 0.012*"of" + 0.012*"coronavirus." + 0.008*"and" + 0.007*"water"'),
 (3,
  '0.032*"the" + 0.020*"to" + 0.016*"in" + 0.015*"a" + 0.013*"of" + 0.013*"are" + 0.011*"coronavirus" + 0.011*"that" + 0.010*"coronavirus." + 0.010*"and"'),
 (4,
  '0.066*"the" + 0.043*"to" + 0.027*"of" + 0.027*"in" + 0.021*"and" + 0.014*"a" + 0.012*"coronavirus" + 0.011*"for" + 0.010*"coronavirus." + 0.009*"that"')]

# Exercise 3

The top-scored words contributing to each topic (if no stopword removal is applied) are english common words (e.g., *to, for, in, of, on*..). Moreover, missing punctuation removal could be critical for topic identification. Add preliminary preprocessing step to:
1. **remove stopwords**
2. **strip punctuation**
3. **lowercase all words**

**Suggestion**: many predefined lists of stopwords are already available. Download the stopword list of NLTK directly in your python code.

In [7]:
## YOUR CODE HERE

import nltk
import string
nltk.download('stopwords')
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))
def preprocess(doc):
    tokens = doc.lower().split()
    tokens = [t.translate(str.maketrans('', '', string.punctuation)) for t in tokens]
    tokens = [t for t in tokens if t and t not in stop_words]
    return tokens

rs_corpus = [preprocess(doc) for doc in df_tmodeling["headlines"].tolist()]

# Rebuild dictionary and processed corpus with cleaned text
tm_dict = Dictionary(rs_corpus)
processed_corpus = [tm_dict.doc2bow(text) for text in rs_corpus]

# Re-train LSI and LDA on cleaned corpus
model = LsiModel(processed_corpus, id2word=tm_dict)
print("LSI topics after preprocessing:")
model.print_topics(5)

lda = LdaModel(processed_corpus, id2word=tm_dict, num_topics=5)
print("\nLDA topics after preprocessing:")
lda.print_topics(5)

[nltk_data] Downloading package stopwords to
[nltk_data]     /davinci-1/home/abuonfiglio/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

LSI topics after preprocessing:

LDA topics after preprocessing:

[(0,
  '0.023*"coronavirus" + 0.018*"covid19" + 0.016*"president" + 0.014*"people" + 0.007*"photo" + 0.007*"health" + 0.006*"trump" + 0.005*"infected" + 0.005*"tested" + 0.005*"hours"'),
 (1,
  '0.040*"coronavirus" + 0.036*"covid19" + 0.014*"people" + 0.007*"video" + 0.007*"pandemic" + 0.006*"new" + 0.006*"government" + 0.006*"predicted" + 0.006*"outbreak" + 0.005*"shows"'),
 (2,
  '0.038*"coronavirus" + 0.027*"covid19" + 0.012*"facebook" + 0.012*"video" + 0.009*"people" + 0.009*"italy" + 0.009*"shows" + 0.008*"novel" + 0.008*"cases" + 0.008*"times"'),
 (3,
  '0.022*"covid19" + 0.016*"coronavirus" + 0.010*"lockdown" + 0.009*"india" + 0.009*"video" + 0.008*"says" + 0.006*"government" + 0.006*"c" + 0.005*"vitamin" + 0.005*"state"'),
 (4,
  '0.086*"coronavirus" + 0.017*"china" + 0.014*"covid19" + 0.013*"new" + 0.013*"video" + 0.012*"chinese" + 0.012*"wuhan" + 0.011*"shows" + 0.010*"water" + 0.009*"novel"')]

In [8]:
# Ri-eseguo aggiungendo una parola in piu alle stopwords per vedere come mabia il risultato
import nltk
import string
nltk.download('stopwords')
from nltk.corpus import stopwords

stop_words = set(stopwords.words('english'))
stop_words.add("coronavirus")
def preprocess(doc):
    tokens = doc.lower().split()
    tokens = [t.translate(str.maketrans('', '', string.punctuation)) for t in tokens]
    tokens = [t for t in tokens if t and t not in stop_words]
    return tokens

rs_corpus = [preprocess(doc) for doc in df_tmodeling["headlines"].tolist()]

# Rebuild dictionary and processed corpus with cleaned text
tm_dict = Dictionary(rs_corpus)
processed_corpus = [tm_dict.doc2bow(text) for text in rs_corpus]

# Re-train LSI and LDA on cleaned corpus
model = LsiModel(processed_corpus, id2word=tm_dict)
print("LSI topics after preprocessing:")
model.print_topics(5)

lda = LdaModel(processed_corpus, id2word=tm_dict, num_topics=5)
print("\nLDA topics after preprocessing:")
lda.print_topics(5)

[nltk_data] Downloading package stopwords to
[nltk_data]     /davinci-1/home/abuonfiglio/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

LSI topics after preprocessing:

LDA topics after preprocessing:

[(0,
  '0.018*"covid19" + 0.013*"facebook" + 0.013*"video" + 0.012*"novel" + 0.012*"china" + 0.010*"new" + 0.010*"shows" + 0.010*"claim" + 0.009*"outbreak" + 0.009*"times"'),
 (1,
  '0.027*"covid19" + 0.011*"vaccine" + 0.009*"people" + 0.008*"new" + 0.008*"chinese" + 0.007*"infected" + 0.006*"masks" + 0.006*"confirmed" + 0.005*"wuhan" + 0.005*"first"'),
 (2,
  '0.019*"china" + 0.017*"people" + 0.014*"covid19" + 0.012*"video" + 0.011*"shows" + 0.010*"health" + 0.007*"infected" + 0.007*"says" + 0.006*"president" + 0.006*"said"'),
 (3,
  '0.017*"covid19" + 0.014*"people" + 0.013*"video" + 0.011*"chinese" + 0.010*"lockdown" + 0.010*"shows" + 0.009*"wuhan" + 0.007*"outbreak" + 0.006*"india" + 0.006*"minister"'),
 (4,
  '0.039*"covid19" + 0.014*"water" + 0.010*"cure" + 0.010*"hospital" + 0.008*"prevent" + 0.008*"kill" + 0.008*"drinking" + 0.007*"virus" + 0.007*"new" + 0.007*"novel"')]

# Exercise 4

Using [pyLDAvis]() library build an interactive visualization for the trained LDA model.

In [9]:
# !pip install pyLDAvis

In [10]:
import pyLDAvis
import pyLDAvis.gensim_models as gensimvis
pyLDAvis.enable_notebook()

lda_display = gensimvis.prepare(lda, processed_corpus, tm_dict, sort_topics=False)
pyLDAvis.display(lda_display)

# Exercise 5

We can also use BERTopic to solve the topic modeling task.

BERTopic is a topic modeling technique that leverages transformers and c-TF-IDF to create dense clusters allowing for easily interpretable topics whilst keeping important words in the topic descriptions.

In [11]:
# !pip install bertopic
# !pip install sympy==1.12

In [12]:
from bertopic import BERTopic

topic_model = BERTopic()
topics, probs = topic_model.fit_transform(df_tmodeling["headlines"].tolist()[:1000])

/davinci-1/home/abuonfiglio/MasterPoliTO/GenerativeAI_master/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/davinci-1/home/abuonfiglio/MasterPoliTO/GenerativeAI_master/.venv/lib/python3.10/site-packages/bertopic/backend/_sentencetransformers.py:4: DeprecationWarning: Importing from 'sentence_transformers.models' is deprecated and will be removed in a future version. Please use 'sentence_transformers.sentence_transformer.modules' instead.
  from sentence_transformers.models import StaticEmbedding
Loading weights: 100%|██████████| 103/103 [00:00<00:00, 10313.78it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [13]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,257,-1_of_the_in_to,"[of, the, in, to, that, coronavirus, for, from...",[Former candidate for the presidency of Brazil...
1,0,89,0_cure_and_coronavirus_prevent,"[cure, and, coronavirus, prevent, can, ginger,...","[The cure for coronavirus: ginger, lemon, onio..."
2,1,80,1_vaccine_the_was_chinese,"[vaccine, the, was, chinese, coronavirus, labo...","[""Plandemia"": This video claims that the coron..."
3,2,75,2_masks_mask_wearing_face,"[masks, mask, wearing, face, oxygen, and, that...",[A video of an excerpt from an American televi...
4,3,42,3_hospital_video_patient_patients,"[hospital, video, patient, patients, covid19, ...",[Doctors of a hospital in New Zealand are chee...
5,4,39,4_brazilian_federal_death_covid19,"[brazilian, federal, death, covid19, no, denie...",[Brazilian Supreme Court denied order for army...
6,5,33,5_more_is_covid19_infectious,"[more, is, covid19, infectious, than, contagio...",[SARS-CoV-2 mutated and became 10 times more i...
7,6,30,6_test_positive_tests_barrier,"[test, positive, tests, barrier, pcr, swabs, b...",[Critics say it is wrong to use of PCR tests f...
8,7,29,7_bill_gates_vaccines_vaccine,"[bill, gates, vaccines, vaccine, microchip, dn...",[Bill Gates was expelled from India due to his...
9,8,29,8_hydroxychloroquine_chloroquine_drug_use,"[hydroxychloroquine, chloroquine, drug, use, a...","[Raissa Soares, a doctor in Bahia, was fired f..."
10,9,28,9_number_cases_only_not,"[number, cases, only, not, deaths, pandemic, a...",[According to a Greek journalist COVID-19 is n...
11,10,25,10_photo_baby_show_which,"[photo, baby, show, which, shows, jair, her, b...",[A picture which would show a mother and her p...
12,11,20,11_picture_italian_conte_economic,"[picture, italian, conte, economic, italy, res...",[A picture of the Italian Prime Minister Giuse...
13,12,19,12_lockdown_ukraine_june_news,"[lockdown, ukraine, june, news, has, schools, ...",[To be able to manipulate the lockdown measure...
14,13,19,13_losing_potency_coronavirus_said,"[losing, potency, coronavirus, said, is, epide...",[WHO said that the novel coronavirus is losing...
15,14,19,14_5g_activated_rna_digitizable,"[5g, activated, rna, digitizable, new, recover...","[The new coronavirus vaccine has ""digitizable ..."
16,15,18,15_boy_predicted_indian_2019,"[boy, predicted, indian, 2019, coronavirus, of...",[A video of a 14-year-old Indian boy named Abh...
17,16,16,16_doctor_hospital_patients_died,"[doctor, hospital, patients, died, muiz, syria...","[A picture of the Egyptian doctor, Mohamed Has..."
18,17,16,17_berlin_august_german_protest,"[berlin, august, german, protest, 1st, governm...",[A picture allegedly showing a large crowd gat...
19,18,16,18_thermometers_infrared_damage_neurons,"[thermometers, infrared, damage, neurons, can,...","[Infrared thermometers kill neurons., Infrared..."
20,19,15,19_whatsapp_message_spain_to,"[whatsapp, message, spain, to, vaccination, it...",[A message accompanied by a photo of a poster ...
21,20,15,20_pedro_pandemic_sanchez_the,"[pedro, pandemic, sanchez, the, spanish, brazi...",[A viral video where an interview from the Tie...
22,21,15,21_ivermectin_african_tunisia_succeeded,"[ivermectin, african, tunisia, succeeded, best...",[The World Health Organization considers Tunis...
23,22,13,22_asymptomatic_official_coronavirus_dont,"[asymptomatic, official, coronavirus, dont, tr...",[Top Georgian health official Gamkrelidze said...
24,23,12,23_happened_odd_hoax_impeachment,"[happened, odd, hoax, impeachment, failed, mom...",[The video allegedly predicted what would happ...
25,24,11,24_melinda_fauci_gates_2015,"[melinda, fauci, gates, 2015, wuhan, obama, la...","[A photo claims to show Dr. Fauci, Melinda Gat..."
26,25,10,25_dead_mexico_bodies_patients,"[dead, mexico, bodies, patients, bags, images,...",[A video on social networks in which you can s...
27,26,10,26_facebook_pandemic_denver_airport,"[facebook, pandemic, denver, airport, painting...",[A painting depicting children in face masks w...

In [14]:
filtered_corpus = [" ".join(s) for s in rs_corpus]

topic_model = BERTopic()
topics, probs = topic_model.fit_transform(filtered_corpus[:1000])

Loading weights: 100%|██████████| 103/103 [00:00<00:00, 7960.59it/s]
BertModel LOAD REPORT from: sentence-transformers/all-MiniLM-L6-v2
Key                     | Status     |  |
------------------------+------------+--+-
embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [15]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,292,-1_covid19_vaccine_claims_pandemic,"[covid19, vaccine, claims, pandemic, claim, vi...",[photo claims show dr fauci melinda gates bara...
1,0,100,0_masks_mask_wearing_face,"[masks, mask, wearing, face, sarscov2, oxygen,...",[video excerpt american television program pre...
2,1,78,1_cure_lemon_ginger_prevent,"[cure, lemon, ginger, prevent, cures, list, co...","[cure ginger lemon onion garlic, cure ginger l..."
3,2,48,2_brazilian_death_video_brazil,"[brazilian, death, video, brazil, hospital, co...",[brazilian city halls receive r 19000 federal ...
4,3,45,3_facebook_times_shared_posts,"[facebook, times, shared, posts, infected, pos...",[multiple facebook posts shared tens thousands...
5,4,39,4_argentina_doctor_died_hospital,"[argentina, doctor, died, hospital, aires, bue...",[picture egyptian doctor mohamed hashad carryi...
6,5,39,5_patient_hospital_video_covid19,"[patient, hospital, video, covid19, shows, zea...",[doctors hospital new zealand cheering video c...
7,6,28,6_test_tests_pcr_barrier,"[test, tests, pcr, barrier, swabs, used, swab,...",[critics say wrong use pcr tests detect covid1...
8,7,28,7_asymptomatic_symptoms_covid19_contagious,"[asymptomatic, symptoms, covid19, contagious, ...",[singapores health ministry issued advisory da...
9,8,27,8_hydroxychloroquine_chloroquine_paulo_use,"[hydroxychloroquine, chloroquine, paulo, use, ...",[scientific study shows cannabis effective pre...
10,9,26,9_picture_august_berlin_german,"[picture, august, berlin, german, protest, con...",[picture italian prime minister giuseppe conte...
11,10,22,10_bill_gates_population_reduction,"[bill, gates, population, reduction, vaccines,...",[bill melinda gates foundation building says c...
12,11,21,11_5g_activated_rna_digitizable,"[5g, activated, rna, digitizable, recovers, re...",[new vaccine digitizable rna activated 5g reac...
13,12,19,12_lockdown_ukraine_june_news,"[lockdown, ukraine, june, news, 2020, motorcyc...",[able manipulate lockdown measures ukraine cla...
14,13,19,13_italy_newspaper_italian_article,"[italy, newspaper, italian, article, stating, ...",[article stating utility bills increased covid...
15,14,18,14_bodies_mexico_dead_sea,"[bodies, mexico, dead, sea, corpses, one, cont...",[picture allegedly shot brazil would show row ...
16,15,16,15_pandemic_since_global_defrauded,"[pandemic, since, global, defrauded, 300000, g...",[according greek journalist covid19 pandemic s...
17,16,15,16_cases_number_tested_positive,"[cases, number, tested, positive, testing, nas...",[covid19 cases big number testing united state...
18,17,15,17_whatsapp_message_50_vaccine,"[whatsapp, message, 50, vaccine, people, post,...",[facebook post claiming 50 million people died...
19,18,15,18_tunisia_border_succeeded_best,"[tunisia, border, succeeded, best, considers, ...",[world health organization considers tunisia b...
20,19,14,19_fear_deaths_1942_2009,"[fear, deaths, 1942, 2009, chuck, yet, attache...",[h1n1 caused deaths 2009 pandemic covid19 yet ...
21,20,14,20_thermometers_infrared_damage_neurons,"[thermometers, infrared, damage, neurons, lase...","[infrared thermometers kill neurons, infrared ..."
22,21,14,21_laboratory_created_china_ghana,"[laboratory, created, china, ghana, president,...",[china using special glasses instead laborator...
23,22,13,22_ivermectin_australia_recommends_symptoms,"[ivermectin, australia, recommends, symptoms, ...","[ivermectin cures new, video man dressed white..."
24,23,12,23_abortion_vaccines_vaccine_plandemia,"[abortion, vaccines, vaccine, plandemia, infan...",[oxford universitys vaccine made using cells a...
25,24,12,24_coronavac_chinese_vaccine_developed,"[coronavac, chinese, vaccine, developed, teste...",[video shows first volunteer vaccinated corona...
26,25,11,25_nipah_outbreak_abdo_isolates,"[nipah, outbreak, abdo, isolates, jeddah, hote...",[singer mohamed abdo infected novel isolates h...

In [16]:
topic_model.visualize_topics()

### **EXTRA**

Use one of the sentence embedding model from the previous practice to cluster the following list of documents:

```python
docs = [
    "Apple unveils new AI features for iPhone users",
    "Microsoft launches a new cloud security platform",
    "Stock markets fall as inflation fears return",
    "Investors expect another interest rate increase",
    "Real Madrid wins after a dramatic extra-time goal",
    "Barcelona signs a new striker for next season",
    "Scientists discover a new method for battery recycling",
    "Researchers develop a model to detect fake news",
    "Parliament debates a new immigration law",
    "Government approves an education reform package",
    "NASA prepares its next mission to the Moon",
    "SpaceX tests a new reusable rocket system",
]
```

Are the documents grouped correctly? Can you think about a way to assign a label to each cluster?

**Suggestions:**
1.   Create the embedding of each document
2.   Pass the embedding to clustering algorithm
3.   Manually check cluster quality

In [17]:
## YOUR CODE HERE